### ISSUE TITLE
Add base Windows image for all plugins

### ISSUE THREAD

**Issue by donny-dont** [drone-plugins/drone-base#6]
There should probably be a base Windows image for all plugins.

**Comment by donny-dont** [comment]
@tboerger can you do all the manifest work here?

**Comment by tboerger** [comment]
That way it would be much easier to update the base image, indeed.

**Comment by donny-dont** [comment]
Can you work on this? I'm happy to update the windows dockerfiles. Should probably test to see if 1709 images can run on 1803 as well.

**Comment by tboerger** [comment]
I didn't get which version exactly you want to use now, but the branch have been created via https://github.com/drone-plugins/drone-base/commit/be4a2f6fe5bb8ae9d9f965920f3e00722845e53e, so feel free to provide a proper version within the Dockerfile and maybe you need to change something at appveyor as well?

**Comment by tboerger** [comment]
Yes, so far each architecture got a separate branch, that's why I have simply named it Dockerfile and not Dockerfile.windows.

**Comment by donny-dont** [comment]
Gotcha ok well if that changes I'll let you deal with it. Just make the changes? I don't think appveyor is 1709 compatible yet.

**Comment by tboerger** [comment]
https://www.appveyor.com/docs/build-environment/#visual-studio-2017 sounds to me like it should be 1709 compatible? Or did I get it wrong?

Just update the Dockerfile and if required the .appveyor.yml
